name: Credit Card Transaction CICD

on:
    push:
        branches:
            - main

jobs:
    run-tests: ubuntu-latest

    steps:
        - name: Checkout Code
          uses: actions/checkout@3

        - name: Set Up Python
          uses: actions/setup-python@v3
          with:
             python-version: "3.11"

        - name: Install Dependencies
          run: |
            pip install -r utils/requirements.txt
       
        - name: Set PYTHONPATH
         run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

        - name: Run Pytest with Converage
        
          